### ISSUE TITLE
Break out the validate function in opa.go

### ISSUE THREAD

**Issue by TheFutonEng** [defenseunicorns-labs/lula1#114]
Currently, in `src/pkg/providers/opa/opa.go`, the [`validate` function](https://github.com/defenseunicorns/lula/blob/main/src/pkg/providers/opa/opa.go) checks on line 27 if the domain is equal to `kubernetes` and then checks on line 54 if the domain is equal to `api` with a functions worth of code contained within various `if` blocks.  

The purpose of this ticket is to refactor opa.go so that the `validate` function is basically a switch statement of some sort with calls to functions depending on the domain. This will make adding domains in the future much easier with a much cleaner pattern to follow for future devs.

Keep me honest with this issue @btlghrants

**Comment by brandtkeller** [comment]
Closed as completed in #358
