### ISSUE TITLE
Support pipeline execution 

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#125]
Lula as a tool in CI/CD will require some modifications to support use as a quality gate. 

If we consider a repository that contains a declarative package that deploys to a kubernetes cluster for testing in CI - then we will want to support the ability to validate against that package as deployed using an OSCAL component definition file. 

This issue encompasses updates to lula to support CI generically:

> Ability to perform a validation in CI given an OSCAL component definition file for the component involved. Assumes a CI pipeline that has deployed a Kubernetes cluster and the declarative package already. 

## Proposed Changes
During validation lula will need the ability to establish a threshold for pass/fail and supporting auditing workflows. 

### Current Thoughts
Establish a `--threshold` flag that can use an existing `assessment-result` as a baseline for comparison when conducting validations. We'll need logic that can compare two assessments and determine when a newer assessment is failing a previously `satisfied` implemented-requirement. This would mean that the validate command can exit with an exit status other than `0` to signify failure.

OR 

Perform the comparison of multiple assessments as a separate command - keeping the `validate` command strictly for generation of the assessment. This would mean that CI processes would need to invoke both a `validate` and a `compare` 

## Future Thoughts
Once we have a defined model for how this works and releases from which to use - I'd like to see a github action built to standardize the execution in GitHub workflows. 

Open to other considerations.

**Comment by gscallon** [comment]
Happy to work and collab on this

Working with customers using GitLab CI/CD, which also has considerations with our product offerings. We can aim to help to work on that aspect of things if that fits in with what you're trying to do.

**Comment by CloudBeard** [comment]
If we went with the --threshold route would we still want to have a compare command? I am thinking about use cases where you'd want to compare assessment-results maybe in but also outside of CI. 

Thinking about Dev experience.

**Comment by brandtkeller** [comment]
Agreed! 

Thinking through the potential `compare` implementation - is this specific to `Lula` or valuable to the greater OSCAL community?

Given it is an `assessment-results` file - I'd say there is broader applicability for use. We'll have to establish some guardrails around what models it is that we can compare when included in `go-oscal`. Generically there will be a desire to see many different documents "Compared" for historical reference. 

IE: 
- Component Definitions 
- Assessment Results
- Assessment Plans
- POAMs
etc

Additional criteria for the compare logic: When a control has been removed. IE an `implemented-requirement` has been removed from the component definition and the new `assessment-results-*.yaml` file no longer contains a finding for a previously validated control.

**Comment by brandtkeller** [comment]
Blocked by https://github.com/defenseunicorns/go-oscal/issues/70

**Comment by CloudBeard** [comment]
I think its valuable to the OSCAL community as a whole. Even if users don't have a validations in their OSCAL but do have multiple versions of large POAMs, Assessment Results, etc an open source easy 1 command way to run a diff on those would be awesome. 

Especially if we can do cross versions. I could see as OSCAL adoption increases we will see some slower adoption of version updates than others it would be great to be able to support that in time too.

**Comment by dgershman** [comment]
I agree this is a good idea, I thought even converting the results to JUnit XML format might be cool too.  One thought I had, is how will we handle the eventual consistency issue of Kubernetes?  Say we deploy a new set of changes, does the pipeline sit and wait until the cluster gets to a steady state (akin to Zarf), and then run it's validations?

**Comment by brandtkeller** [comment]
That's a really good question @dgershman . eventual consistency is why there is a reduced priority around writing logic for supporting static manifest validation. Still an option but not highest priority.

To that end - I wonder if we can make the assumption that the developer knows the intended eventual state and we could add a command to wait for a specific state before running validation in a pipeline?

**Comment by dgershman** [comment]
Yes, something like that I think will suffice.
