### ISSUE TITLE
no such file or directory: ./lula

### ISSUE THREAD

**Issue by chadmcrowell** [defenseunicorns-labs/lula1#139]
In the getting started guide, running the `./lula validate ./demo/oscal-component.yaml` command from within the `lula` directory resulted in the following error:

```bash
$ ./lula validate ./demo/oscal-component.yaml                                                                                                                    [12:37:10]
zsh: no such file or directory: ./lula
FAIL
$ pwd                                                                                                                                                           [12:41:24]
/Users/user/lula
```

please advise.

**Comment by brandtkeller** [comment]
Great call out @chadmcrowell ! This was also recently mentioned in #130 - we need to update the instructions. Barring any other movement I will get this fixed asap!

Intent: 

After the `make build` step the binary is more accuretely located in the created `bin/` directory within the Lula project. 

So `./bin/lula validate ./demo/oscal-component.yaml` would be the correct execution if all other dependencies have been met.

**Comment by brandtkeller** [comment]
Updated the README instructions for the demo. Please feel free to re-open this issue if any problems persist.
