### ISSUE TITLE
Evaluate SAR implementation for each evaluation

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#147]
Currently we produce a new assessment-results file each time execution. We should evaluate this versus creation of a new file or appending to an existing file when identified.

**Comment by brandtkeller** [comment]
Also consideration for doing/allowing both. 

## Validation
From the validation perspective - add a flag to indicate the assessment results file to write the new content to. If the file doesn't exist - create it (allows for explicit naming of the target file). If the file does exist - write a new `result` to the `results` array. Update any fields as required (metadata, uuid, etc).

When not specified - write to a unique file (timestamp) as is standard convention to-date.

## Comparison
Comparison should be looking for assessment results to compare findings. Given that we should expect assessment results to potentially contain many `results` - I believe it is our responsibility to choose and document intended behavior. Two files for comparison should by default compare the latest findings in each. 

If the comparison only receives one file - it should attempt to compare the latest result to the result that preceded it.

**Comment by CloudBeard** [comment]
I agree on the comparison command functionality. Default is to compare the most 2 recent result in the results array.

Less commands/more simplistic for that use which may be more common while still supporting the opposite that if you wanted to compare two separate files you include the files. From the Assessment results perspective.

The use case I am thinking a mission hero has two environments using the same capabilities and one environment may be different than the other and this could help narrow down what/why.

**Comment by brandtkeller** [comment]
> The use case I am thinking a mission hero has two environments using the same capabilities and one environment may be different than the other and this could help narrow down what/why.

This is where a generic compare for all models would be valuable. I wonder if we should change terminology on this to indicate performing an evaluation of whether a new assessment result meets all of the controls satisfied in a previous assessment result.

`Lula eval`?

**Comment by CloudBeard** [comment]
That may come across easier to folks first seeing it. Compare to compare files to each other and eval for evaluating two result in the results array.

I was thinking about what it would like and I think a different command is easier to see that separation instead of if you add 1 or 2 files.
