### ISSUE TITLE
OSCAL Schema compliance for extended oscal component definition

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#15]
Update the oscal-component.yaml documents and surrounding logic to be compliant with OSCAL schema.

**Comment by brandtkeller** [comment]
Recommended to review [The Orion JK21 Collaboration for Agile ATO](https://atarc.org/wp-content/uploads/2022/03/ATARC_Cloud-Security-Working-Group_Report-2-28-2022_FINAL.pdf)  to guide possible iterations.

**Comment by brandtkeller** [comment]
Looking at the schema for component-definition - curious if we can utilize `implemented-requirements.props` to point to an artifact in back-matter resources (using UUID's). 

Would this be a single artifact that housed some data format for all control validation or would they be separate? separate sounds like a painful user experience.

Back-matter resources:
> 1) it may point to an specific retrievable network resource using a rlink, or 2) it may be included as an attachment using a base64

Is there a format we could define as a common layer between OSCAL and some future CRD. Need to look at what data is required for transient flow from execution to report.

**Comment by brandtkeller** [comment]
Worth considering the above points made here previously. 

Other items I would like considered:

### Organization and UX

IE How easy is the validation presented. I don't love the base64 encoded option as it obfuscates what is happening and adds additional burden for encoding/decoding to the developer experience. 

### OSCAL Data types

If possible - we want to reduce any custom type/ modification to the upstream (go-oscal) types. Can we ingest an existing type and parse the content for a lula validation? 

### Future development 

What does the landscape of changes look like for OSCAL? (what happened to the rules/checks proposal - investigate) - What would optimal look like for the ecosystem? Could we propose a change in the future as we learn more? (answer here is always yes)

**Comment by Alvin-zzz** [comment]
Research OSCAL NIST GitHub's OSCAL component schema to find deltas and changes.

https://github.com/usnistgov/OSCAL/blob/main/src/metaschema/oscal_component_metaschema.xml

**Comment by brandtkeller** [comment]
Documenting conversation for posterity:

## Back-matter reference

One possible solution is to align with an OSCAL suggested extension mechanism for [Referencing Back-Matter](https://pages.nist.gov/OSCAL/learn/tutorials/general/extension/#referencing-back-matter). 

This might look something like an `implemented-requirement` containing a `link` with a `text` identifier for a Lula payload and referencing a uuid to a `resource` in the back-matter. 

The `resource` in the back-matter could potentially use `UUID` for reference, `title` indicating a lula payload and `description` containing the payload itself. 

### Optimizations
With this solution, the de-duplication of potential validations becomes easier. Each validation would have a unique identifier and thus caching becomes easier.

**Comment by Alvin-zzz** [comment]
Research, JSON reference.

https://pages.nist.gov/OSCAL-Reference/models/v1.1.0/complete/json-reference/

**Comment by Alvin-zzz** [comment]
### Backmatter Reference

We might be able to use a Citation, and underneath that we can use props to house the payload.
