### ISSUE TITLE
Update lint command following go-oscal validate updates

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#157]
https://github.com/defenseunicorns/go-oscal/pull/77

Will need to follow suit for consuming the `ValidateCommand` function.

**Comment by mike-winberry** [comment]
Waiting on go-oscal release.

**Comment by CloudBeard** [comment]
Blocks testing for a couple of commands in Lula. 

Creating those tests should be an easy lift.
