### ISSUE TITLE
Reporting of number of controls met by component definitions

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#223]
### Is your feature request related to a problem? Please describe.

Ability to report on the number of controls present in a component definition - filtered by control-implementation source and framework. 

### Describe the solution you'd like

- **Given** a component definition is present
- **When** `lula` report is executed
- **Then** a report logged to stdout to capture number of controls based on the above filter

### Additional context

This would pave the way for future reporting on percentage of controls (when Lula can properly process both catalogs and profiles).

### Expected Deliverable

- [ ] Report Command added
- [ ] Ability to ingest component-definition files (error otherwise)
- [ ] Aggregate number of controls by control-implementation source and framework
- [ ] Log report to stdout
- [ ] Tests
- [ ] Docs

**Comment by brandtkeller** [comment]
```mermaid
flowchart TD
    A[Report] -->|default/specified OSCAL files| B(Build Report)
    B --> C{Check for existence of models & Collect/identify Catalog}
    C -->|Components Exist| D[Component Report]
    C -->|SSP Exists| E[System Report]
    C -->|Assessment Results Exist| F[Assessment Report]
```

**Comment by CloudBeard** [comment]
That makes perfect sense ^

**Comment by CloudBeard** [comment]
Need to swap my tests back around before re-review
