### ISSUE TITLE
Creation and validation of OSCAL Component Files

### ISSUE THREAD

**Issue by Alvin-zzz** [defenseunicorns-labs/lula1#228]
- How are we going to create new OSCAL component files for new systems/packages?
- How are going to re-use data from other systems for controls?
- How do we automate the structure/schema for Lula component files?

**Comment by brandtkeller** [comment]
As we evaluate the ability to generate OSCAL - this should definitely be a workflow evaluated for inclusion.

Bootstrap a new Component-definition file with any and all information that we have context about. 

Given that we use the component-definition model - the file should be schema compliant when the file is written to the filesystem.

**Comment by brandtkeller** [comment]
Closing as a duplicate of #272 which contains more context
