### ISSUE TITLE
Terminalizer Demo

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#23]
https://github.com/faressoft/terminalizer#usage

add to readme

**Comment by corang** [comment]
What did we want to demo?

**Comment by brandtkeller** [comment]
As a potential user of Compliance Auditor, I would like to see quick demo embedded in the repository for how the tool is used and expected behavior.

I'd say we target both cluster and manifest in a single demo. We can skip past the build and just demo the `execute`.

At a minimum - the manifest version would provide a lot of great context without anything more than the repository cloned and the tool built.

**Comment by brandtkeller** [comment]
Initial demo's were added as part of https://github.com/defenseunicorns/compliance-auditor/pull/29
