### ISSUE TITLE
Add enhanced logging to OPA provider

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#255]
For debug or above logging - it might benefit Lula to produce insights into:

- the dataset being validated
- decisions being made in rego and/or their outcomes

Goal here being to improve debugging processes for payload developer experience.

**Comment by meganwolf0** [comment]
Have been trying to pull some data on what was going into the rego function for this purpose - it might be nice to implement like a `dryrun` on validate to print the rego and expected payload so a dev could take those two and paste them in like the rego playground and then interrogate the rego script a bit more there - I used this snippet in the opa.go `GetValidatedAssets` and it worked well
```go
jsonData, err := json.MarshalIndent(dataset, "", "    ")
if err != nil {
    log.Fatalf("Error marshaling to JSON: %v", err)
}

// Print JSON string
fmt.Printf("Dataset: %s\n", string(jsonData))
fmt.Printf("Rego Policy: %+v\n", regoPolicy)
```

I think it's hard to get specific rego outcomes this way, the playground is where I go personally to break things down more. I think the completion of this [issue](https://github.com/defenseunicorns/lula/issues/265) might help at least printing more variables to the assessment results

**Comment by brandtkeller** [comment]
`lula dev` commands have been introduced to begin aiding in the development process of a providers policy and the resources associated for evaluation.
