### ISSUE TITLE
Lula terminology around commands

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#257]
Recent discussion has highlighted that there overloaded terminology around the verbs used in compliance, OSCAL and the initial commands Lula has used to-date.

IE validate in OSCAL might more accurately describe validation of the OSCAL artifact itself rather than an action that is performed against a given environment. 

Given the action Lula is performing - Ultimately abstracted to be assessment given an `assessment-plan`  - we may want to investigate the use of other more correct terminology. 

`lula assess`, etc

@imichaela Does that align well to your previous points?

**Comment by CloudBeard** [comment]
`lula validate` -> `lula assess`

Not sold on swapping evaluate to check the difference between 2 similar OSCAL types.
`lula evaluate` -> `lula differential`

**Comment by brandtkeller** [comment]
scope: rename files, functions, and command to reflect the change for `lula validate` -> `lula assess`

**Comment by brandtkeller** [comment]
Moving out of release to assess scope

**Comment by CloudBeard** [comment]
PR for this lives in another repo than Lula. https://github.com/defenseunicorns/compliance-artifacts/pull/35

**Comment by brandtkeller** [comment]
Initial PR merged into `compliance-artifacts`
