### ISSUE TITLE
Use data from resource fields for validation

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#289]
Certain resources contain data in undefined formats (e.g., ConfigMaps, Secrets, perhaps even custom resources), additionally annotations and labels may do so as well. This is difficult for rego to parse as it gets read in as a string conversion of those undefined types. This data would be more usable by the rego validation script if the underlying data type was specified, converted, and given to OPA provider in an expected JSON format. It may also be beneficial if the data can be base64 decoded in cases where applicable.

This issue should look at how to extend the resource type to account for fields, possibly decoding them, in various formats, and providing that data to the OPA provider so that the rego script can access the fields and perform validation on the data.

**Comment by brandtkeller** [comment]
Appreciate this idea as a method for making the payload more descriptive and require less Rego magic. 

What assumptions do you believe we can make about the target? 
- name?
- field(s)?

Is this an opt-in process that assumes you know what you are intending to target? (Less wildcard/dynamic and more strict)

**Comment by meganwolf0** [comment]
Yeah, I think this would be fairly targeted to a specific field, perhaps a specific resource but I think you could batch grab. I was toying with the type changes and a possible implementation could be - for types.go:
```go
type FieldType string

const (
	FieldTypeJSON FieldType = "json"
	FieldTypeYAML FieldType = "yaml"
)

type Field struct {
	Jsonpath string    `json:"jsonpath" yaml:"jsonpath"`
	Type     FieldType `json:"type" yaml:"type"`
	Base64   bool      `json:"base64" yaml:"base64"`
}

type ResourceRule struct {
	Name       string   `json:"name" yaml:"name"`
	Group      string   `json:"group" yaml:"group"`
	Version    string   `json:"version" yaml:"version"`
	Resource   string   `json:"resource" yaml:"resource"`
	Namespaces []string `json:"namespaces" yaml:"namespaces"`
	Field      Field    `json:"field" yaml:"field"`
}

// Validate the Field type if valid
func (f Field) Validate() error {
	switch f.Type {
	case FieldTypeJSON, FieldTypeYAML:
		return nil
	default:
		return errors.New("field Type must be 'json' or 'yaml'")
	}
}
```

for the resource itself, maybe something like
```yaml
resources:
  - name: tempoconfig
    resourceRule:
      Name: tempo-config
      Group:
      Version: v1
      Resource: configmaps
      Namespaces: [tempo]
      Field:
        jsonpath: .data.foo.json
        type: json
```
Then I was thinking you'd get something back to the opa provider that would be an array called `tempoconfig` with the data specified by the field, converted from json string or yaml string to json (I think these are probably the most common/easiest but I guess you could extend to other types). In this case it would only be a single entry since the name of the configmap is also specified, but if you were pulling a bunch of elements with identical fields and evaluating it would just be an array of all those things - similar to how resource is done, just that field data instead of a resource data. Would definitely require more from the person creating the resource to understand the requirements but hopefully error handling would help with that.

**Comment by meganwolf0** [comment]
@brandtkeller - noticed you dropped this in the backlog - was thinking that this feature would be pretty valuable to providing better validation results for some of the validations (particularly seeing spots where this would be useful in the course of tempo and promtail validations) so I'm thinking I might spend a little time running this down further unless you'd like me to keep this in the backlog and work something more pressing.

**Comment by brandtkeller** [comment]
@meganwolf0 bumped priority and moved into the current iteration 👍
