### ISSUE TITLE
Docs website skeleton creation

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#292]
Create the skeleton for the Docs website. Ability to capture variations of the website by release would be preferred. 

## Objectives
- Skeleton layout for implementing multiple groups of sub-pages (IE topic and relevant sub-pages)
- Ability to select docs by a given release

**Comment by andrewg-xyz** [comment]
related: https://github.com/defenseunicorns/growth/issues/43

@brandtkeller We are here to help :) I owe you a bit more detail on what we plan to have in place in order to support the objectives you outlined here.

**Comment by brandtkeller** [comment]
Completed with the migration to a separate docs repository: https://github.com/defenseunicorns/lula-docs
