### ISSUE TITLE
Lula minimum versioning

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#294]
Due to the pace of development, new features are being added that might impact how external data (e.g., validation OSCAL) is handled. For instance, two recent issues change the ability to [use named resources](https://github.com/defenseunicorns/lula/issues/249) and [specify outputs](https://github.com/defenseunicorns/lula/issues/265) from the rego provider. For these, the `payload` structure has changed in the back-matter descriptions and those should at least be pinned to minimum Lula versions to ensure that they work as expected.

One possibility could be to augment `target` with a lulaVersion field, such as:
```yaml
target:
   lulaVersion: >= 0.2
```

**Comment by brandtkeller** [comment]
Can this be an optional field where we implicitly assume that there is compatibility _but_ if the field is specified _and_ the executing version is less than the declared - we produce an error?

We haven't introduced any breaking changes just yet - but this could also be an enabler for cross-version compatibility.

**Comment by meganwolf0** [comment]
I'd be interested in other thoughts here, I'm kind of on the side of mandating version - I think mainly because the data is living separate from the tool and that version is really the only traceability to assumptions made about the data structure at the time it was created. So when a user creates and tests a policy I would sort of expect them to just document the version - assuming backward compatibility for all future versions I think is mostly fair so ideally it's a parameter set once at the time of creation and not needed to be revisited

As a thought experiment, we have a new resource "field" PR  - so if I update the tempo.yaml and pull some resource fields but it somehow it gets run against the current release of Lula it would just err out I think due to mismatched types. Maybe that's ok? But a user who didn't understand the versioning mismatch might be left confused with why the types don't match. I think just with the fact that these artifacts may spread far and wide, being specific on enforcing assumptions could be beneficial.

Again, just mostly my gut feelings about it but probably a good discussion topic for grooming!

**Comment by brandtkeller** [comment]
It certainly becomes more valuable if required - An error due to version compatibility becomes something for which we can wrap in a nice error message. Need to think about the pro/cons for each stance.

**Comment by brandtkeller** [comment]
Documentation for posterity: 
- Create an optional `target.lulaVersion` field
- This sets a standard for establishing constraints for version compatibility
- If the executing version of Lula is non-compliant with the `targetVersion` - log the version incompatibility to the observation and mark the finding as `not-satisfied` - do not run the validation
- Need to validate functionality when building from source w/ `make`
- Add documentation to capture assumptions and expectations
