### ISSUE TITLE
Improve API domain optionality

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#356]
The `api` domain currently is very generic and does not accept any configuration that may make it valuable. 

## Objectives
- Research and define required configuration (tokens, credentials, etc) that may be useful for the API domain to request meaningful data from various services. Does any tooling do this today?
- Careful consideration for secrets use and management

## Deliverable
- [x] Design Doc outlining Proposed architecture with alternatives
- [x] Issues decomposed and attached to milestone
- [x] #765
- [x] #769
- [x] #787
- [x] #800
- [x] #825
- [ ] Add HEAD
- [ ] Documentation for Head

**Comment by brandtkeller** [comment]
Moving to blocked by #517 as this configuration support may be a pre-requisite

**Comment by mildwonkey** [comment]
Design doc(internal link): https://coda.io/d/Product_dGmk3eNjmm8/API-Domain-Review_suJOX_sP#_lu6R8wP8

**Comment by mildwonkey** [comment]
I'd like to suggest that we close this issue (once the latest documentation PR is merged) - HEAD won't be hard to add but (like PostForm) I think it's better to wait for users asking for it and instead find more immediately relevant things to work on. what do you think?

**Comment by mildwonkey** [comment]
Update ^^ After discussion (and updating the design doc to also capture this), we are calling the API domain optionality work complete! The remaining methods I wanted to support (PostForm and Head) are fine ideas, but it's not clear if anyone wants or needs them, so at this point we're best off waiting for actual user feedback before adding more code. Hooray for not writing DOA code! 😂 

I'll close this once the last little docs PR is merged

**Comment by mildwonkey** [comment]
(closed by mistake)
