### ISSUE TITLE
Check if Lula Validation is malformed and include in output for rationale on satisfaction decision

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#364]
Right now, if you have a Lula Validation that is successfully unmarshalled but doesn't have the needed fields for evaluation, it returns a "not-satisfied" with no additional rationale. It would probably be good to do like a lint check on the validation yaml structure as part of `validate` to determine that it's actually being interpreted correctly.

**Comment by brandtkeller** [comment]
To follow: #290

**Comment by mike-winberry** [comment]
- [ ] depends on https://github.com/defenseunicorns/go-oscal/issues/246

**Comment by meganwolf0** [comment]
This issue was written separately, but the implementation also closes #360
