### ISSUE TITLE
Add input resources.json to dev validate command 

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#385]
### Is your feature request related to a problem? Please describe.
This may not bucket in `dev validate` and may possibly be a separate command, but it would be beneficial to have the ability to pass in resource.json to the command to execute expected validations. This is particularly useful in testing of policy, where you'd have a different expected outcome for different resource test cases. It's not realistic to have to modify the cluster to match the scenario, so it would be easier to just change the resource json. This would also support having some documentation of test cases ran against each validation.

### Describe the solution you'd like

- **Given** I have different resource json that map to different validation outcomes (True/False)
- **When** I want to test a Lula validation
- **Then** I'm able to choose those resources + pass an expected validation outcome

### Describe alternatives you've considered
None

### Additional context
None

**Comment by brandtkeller** [comment]
Agree with the intent - I believe there may be a common thread to pull between this logic and the requirements in supporting the ability to [reproduce an observation](https://github.com/defenseunicorns/lula/issues/301)

**Comment by brandtkeller** [comment]
Discussed how this is going to be part of a few additions to validation development that would make a significant impact. Moving out of triage to `ready`.
