### ISSUE TITLE
CLI Testing

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#450]
### Describe what should be investigated or refactored

Currently we have no tests to evaluate the CLI commands and flags.

### Links to any relevant code

None

### Additional context

It would be good to evaluate and implement Lula CLI testing to ensure a robust CLI experience for users and better methods for developers to evaluate how changes impact the system.

**Comment by brandtkeller** [comment]
Current progress is retroactively adding tests in `src/test/e2e` as executed through the CLI commands themselves. Closing this with intent to file specific issues for areas that need to be cleaned up.
