### ISSUE TITLE
Validation Review Fields/Process

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#460]
### Is your feature request related to a problem? Please describe.
Capture processes and enhancements to the validation process for how a validation is/should be tested. 

### Describe the solution you'd like

- **Given** a decomposed validation exists
- **When** dev validate is executed
- **Then** context and processes are present to test pass/fail scenarios

### Describe alternatives you've considered
Perform this as an isolated process from Lula

### Additional context
This could be additional fields in the validation that support how to test the validation. 

Should we trim these off when composing?

**Comment by meganwolf0** [comment]
Initial cut at solution in #667 - still missing some functionality but I think the doc highlights where it's going
Took the stance that tests should exist in the validation, so I think the composed/decomposed conversation is possibly moot with that implementation. As to whether those should be trimmed... I could possibly see a case for wanting to re-test the validation on the actual resources in the environment to ensure it's continually relevant? I'm thinking maybe for more of the long-lived system/continual evaluation piece

**Comment by brandtkeller** [comment]
Discussion - create a design doc
