### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns-labs/lula1#47]
Why do we need this?

- To help guarantee we're providing users quality, reliable software
- Keep our code and architecture as clean as possible
- Gives us confidence that changes we make to the code base were safe and work as expected

Possible solutions:

- Unit tests for pure, algorithmic type functions that do not manage any sort of state directly, and produce predictable output
- End-to-end/integration tests to ensure Lula works as expected in a Kubernetes environment. As [Lula will likely run as a Kubernetes controller in a Kubernetes cluster](https://github.com/defenseunicorns/lula/blob/main/docs/ARCH.md#execution), and the [zarf-controller](https://github.com/defenseunicorns/zarf-controller) uses [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder), we could look at [these docs](https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html) that discuss testing kubebuilder k8s controllers. We should also look into re-using testing components from Zarf for running e2e cli tests.

**Comment by AvineshTripathi** [comment]
I would love to try soling this issue if no body is working on it.

**Comment by brandtkeller** [comment]
Hi @AvineshTripathi, we'd love to have you on-board. 

I have not implemented labels properly and that may lead to some confusion. Right now we're in an investigation phase. I'd say #39 is likely a blocker for this. There may be some foundation we could provide - but ultimately we need to select an underlying framework or engine for how we write compliance policy and perform a comparison against live/static assets.

I plan to engage more frequently in that issue and would love to get your thoughts and any code you see fit that could help influence the selection of engine(s). I will get an update into that issue for current state shortly!

**Comment by CloudBeard** [comment]
Partially implemented through PR: https://github.com/defenseunicorns/lula/pull/178

**Comment by CloudBeard** [comment]
Looking for feedback on the process of testing for when we don't have direct access to the functions but need to follow something like an integration test style.

**Comment by brandtkeller** [comment]
Closing this issue in favor of creating smaller-scoped issues with more definition.
