### ISSUE TITLE
Automated dependency updates

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns-labs/lula1#48]
Why do we need this?

To ensure we keep our dependencies up-to-date with minimal manual effort. Keeping our dependencies updated ensures we are getting any latest bug fixes, security patches, or new features from upstream.

Possible solutions:
- [Renovate](https://docs.renovatebot.com) would keep us consistent with [Zarf](https://github.com/defenseunicorns/zarf/blob/main/renovate.json)
- [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) may be a bit more simple to configure with minimal YAML

**Comment by CloudBeard** [comment]
Initial renovate [pr](https://github.com/defenseunicorns/lula/pull/85#pullrequestreview-1688401691) out

Will need updated over time as we add more dependencies.

**Comment by CloudBeard** [comment]
Merged!
