### ISSUE TITLE
Automated vulnerability scanning

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns-labs/lula1#49]
Why do we need this?

To ensure our code and it's dependencies are not vulnerable to CVEs, and to be aware if we are affected so that we can quickly fix it.

Suggested solution:

We should stay consistent with using what Zarf uses for this, which currently is [grype](https://github.com/anchore/grype).

See the [github workfow zarf uses for running the grype scans](https://github.com/defenseunicorns/zarf/blob/main/.github/workflows/scan-cves.yml)

**Comment by CloudBeard** [comment]
## Tool
Choosing Grype would be good to stay consistent with Zarf. 
(Internal Compliance Note)

## Vulnerability Severity
Should we fail a build based on severity? IE Critical, High, Medium, Low

Benefits would be for internal compliance and help prevent shipping with known vulnerabilities that have patches.

## Issues
If we choose to fail a build based on severity it is possible that the vulnerability hasn't been patched yet. That said we can ignore that vulnerability in the .grype.yaml file and make note that the vulnerability has not been patched yet.

## Ouput
Do we want to output to the security section for now?
(Internal Compliance Note)

**Comment by CloudBeard** [comment]
## Tool
We should also include OSSF Scorecard which checks for more overall vulnerabilities surrounding the repo not just the code its self. https://securityscorecards.dev/#what-is-openssf-scorecard

## Why
- Scorecard is also used by Zarf and Pepr
- Helps to show the security of the repo.
- Is an OSSF tool (pilot running for OSSF Allstar)

**Comment by CloudBeard** [comment]
PR has been merged.
