### ISSUE TITLE
Lula Lint on Multiple OSCAL Models in OSCAL.yaml

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns-labs/lula1#493]
### Environment
Device and OS:  Ubuntu 22.04
App version: v0.3.0    

### Steps to reproduce
1. Start with an already existing OSCAL component definition that successfully passes lula lint named `oscal.yaml` (Name dosen't matter as long as everything is ran against that name but default makes the commands quicker)

2. run `lula validate -f oscal.yaml`

3. run `lula tools lint -f oscal.yaml`

### Expected result
`Successfully validated oscal.yaml is valid OSCAL version 1.1.2 component-definition`

### Actual Result
`ERROR:  Failed to lint oscal.yaml`

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/lula/assets/61879371/3561226f-dd67-4157-a31c-c264012462a6)

### Additional Context
Lula supports validating/evaluating combined oscal models in a single oscal.yaml document. We may also need to support linting the combined model.

**Comment by mike-winberry** [comment]
I believe we have a story open for this in go-oscal, since oscal's schema doesn't allow it, we may have to doctor our schemas or pull the yaml apart since by default a multi model oscal file is invalid according to the schema

**Comment by CloudBeard** [comment]
Ah found it https://github.com/defenseunicorns/go-oscal/issues/217

**Comment by CloudBeard** [comment]
Closing as duplicate issue.

**Comment by mike-winberry** [comment]
https://github.com/defenseunicorns/go-oscal/issues/217

I can bump priority if needed now and knock that out after integrating v0.5.0 of go-oscal for the other story,

oh lol found it.
