### ISSUE TITLE
Assessment Findings don't account for multiple components evaluating against the same Control ID

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#500]
### Environment
Device and OS:  
App version:    
Kubernetes distro:  
Kubernetes version:  
provider:
- [ ] kyverno
- [ ] opa

### Steps to reproduce
1. Aggregate multiple components that specify the same control
2. `lula validate -f <oscal.yaml>`

### Expected result
Assessment results model should report on each Finding, or at least document the individual implemented requirement text/information

### Actual Result
Findings takes only one implemented requirement text/data, which omits information that might be relevant/important from other implemented requirements

### Severity/Priority
Medium

### Additional Context

**Comment by brandtkeller** [comment]
@meganwolf0 Can you elaborate on:
> Assessment results model should report on each Finding, or at least document the individual implemented requirement text/information

Is this with respect to a `Finding` description only being from one `implemented-requirement`?

**Comment by meganwolf0** [comment]
> @meganwolf0 Can you elaborate on:
> 
> > Assessment results model should report on each Finding, or at least document the individual implemented requirement text/information
> 
> Is this with respect to a `Finding` description only being from one `implemented-requirement`?

Yeah - basically that only the text from one implemented requirement is pulled into `findings.description`, so you're losing some info there if there are multiple components implementing the Control
