### ISSUE TITLE
Support for templating configuration data

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#517]
### Is your feature request related to a problem? Please describe.
In order to create an SSP, we need to have external data (e.g., system characteristics, metadata, etc.). The idea of external data may also apply to other workflows, such as running API requests (as part of the API domain), performing templating of validations, and generating other OSCAL artifacts. 

### Additional context

First thoughts that the satisfaction of this could be done via the [viper](https://github.com/spf13/viper) library

### Issue Deliverables

- [x] Research and document context required to drive gap analysis and option evaluation
- [x] Decompose issues into `small` weight scope

**Comment by brandtkeller** [comment]
This issue should probably comprise setting up the underlying infrastructure for how we set/get configuration data (config files / env vars / `--set` etc). Additional issues can then be scoped for templating "layers":
- Templating for OSCAL Generation
- Templating for Validations
- Templating for domain secrets

**Comment by brandtkeller** [comment]
Research and Evaluation has lead to agreement to pursue this issue with the intent to add context to implementation - as the research ultimately lead to implementation details that were seeking common outcomes (and less about concrete evidence of disparate processes that required thorough review). 

Capturing current intent in #551 and moving forward with proposing updates through implementation of outcomes in follow-on issues. 

With the research documentation captured in the draft PR and Issues created (See mentions) - this issue and associated draft PR can be closed.

**Comment by brandtkeller** [comment]
Closing as research has been completed with issues decomposed
