### ISSUE TITLE
Deterministic OSCAL Writes

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#542]
### Is your feature request related to a problem? Please describe.
When lula performs a write (whether in isolation or with a merge) the models use of arrays lead to random ordering of objects. 

As lula encourages the version control of OSCAL and the review of changes - it will become more pertinent that the changes reflect the modified lines and not mass-updates due to changing order of existing/not-modified items. 

### Describe the solution you'd like

- **Given** an operation that performs oscal writes
- **When** an oscal file is generated
- **Then** the order for performing the same action is the same

### Describe alternatives you've considered
No Alternatives

### Additional context
Each model needs consideration for array use and performing a sort on some key. 

`lula generate component` may be a good starting point given the easy identification of many nested objects.

**Comment by mike-winberry** [comment]
Can you clarify Arrays, Are you saying the things of type `array` are being shuffled? or are we just talking object keys? Cause if so, something is wrong with go lol. Or the json and yaml packages, because that's always a violation of json/yaml
