### ISSUE TITLE
[Question] Namespace level in docs

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#579]
Not so much a feature request as a question/nit on the docs - The `namespace` docs appear at the top-level menu in the Lula docs, wondering if this would make more sense as a subset of OSCAL, since that's the context in which `namespace` is defined?

Just wanted to raise it as a question/possible move, it feels a little out of place to me right now

### Proposed Solution
Move `namespace` directory under `OSCAL`

### Expected Deliverable

Add a constant for the props `namespace` value

Updating props internal to validate/evaluate to point to the new namespace url

generate updates to update a prop ns from the old url to the new

**Comment by brandtkeller** [comment]
I agree that it intuitively should live underneath the `oscal` directory. 

The only drawback is that we'll need to consider our current `props` use (threshold, framework, target etc) that current resolve to `https://docs.lula.dev/ns` and either update as a breaking change or provide backwards compatibility under-the-hood.

**Comment by meganwolf0** [comment]
> The only drawback is that we'll need to consider our current `props` use (threshold, framework, target etc) that current resolve to `https://docs.lula.dev/ns` and either update as a breaking change or provide backwards compatibility under-the-hood.

Yeah that's a fair point. I think probably just an update with a note would suffice? Does a broken link break any kind of oscal linting?
