### ISSUE TITLE
Validation refactor

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#625]
### Describe what should be investigated or refactored

With the extension of the validation function - particularly in the number of options provided and current handling of those - it would probably be beneficial to refactor this function to reduce side effects and make testing cleaner. One option is to utilize the [functional options pattern](https://golang.cafe/blog/golang-functional-options-pattern.html).

This might also include thoughts about refactoring some of these methods to library functionality, where relevant.

### Links to any relevant code

[validate cmd](https://github.com/defenseunicorns/lula/blob/main/src/cmd/validate/validate.go)

### Additional context

none

### Expected Deliverable

Discussion on best refactor path 

Refactor, implementation

Any relevant changes to end-user options captured in documentation

**Comment by brandtkeller** [comment]
Curious if when the time comes to implement an `assess` command for `assessment plans` if we'll hit another refactor position.

**Comment by meganwolf0** [comment]
> Curious if when the time comes to implement an `assess` command for `assessment plans` if we'll hit another refactor position.

Since we don't have the command yet, I'm not sure what would be refactored? Other than saying we'd like to go with a different construct for building commands... I personally like the `options` construct, I feel like it makes things cleaner and more idiomatic in scaffolding the required fields when implementing those commands but 🤷‍♀️ 

(PS I'm guessing you revisited this one because it's possibly closed by #708 )

**Comment by meganwolf0** [comment]
@brandtkeller I think this might be closed as of #708 - let me know if you agree :)

**Comment by brandtkeller** [comment]
Agreed - closing as complete
