### ISSUE TITLE
Console testing

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#627]
### Describe what should be investigated or refactored

Add Testing to console/tui packages 

### Additional context

Explore using teatest vs custom unit tests for models vs some other test framework out there(?)

### Expected Deliverable

Tests!

**Comment by brandtkeller** [comment]
For posterity - having more success currently with the use of golden files and `FinalModel()` in place of `FinalOutput()`

See this [testing draft](https://github.com/defenseunicorns/lula/pull/634)
