### ISSUE TITLE
Template files during persistent writes

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#642]
### Is your feature request related to a problem? Please describe.

Ability to perform templating during compose or retain original templates 

### Describe the solution you'd like

- **Given** templates in an oscal file
- **When** compose is executed
- **Then** optionality to either template the non-sensitive fields or retain templates during file write

### Additional context

We will likely want the ability to support both

### Expected Deliverable

- [ ] Compose supports retaining templates (default)
- [ ] Compose supports performing templating with a flag

**Comment by brandtkeller** [comment]
Decomposed from #517

**Comment by meganwolf0** [comment]
Per conversation with @brandtkeller - going to backlog this issue for now until a tangible use case for implementing templating in `lula tools compose` can be established. Current thoughts are that assuming valid `component-definitions` are injected into the compose process (e.g., the input file and imported component-definitions) then the implementation of template during the execution of `compose` would simply wrap functionality that is already exposed by `lula tools template`.

**Comment by meganwolf0** [comment]
After further evaluation of `lula validate` and thinking through more compose use cases, going to re-prioritize this issue to complete before the `validate` implementation
