### ISSUE TITLE
Add console documentation for supported models

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#654]
### Describe what should be investigated or refactored

Mention of working with console and not seeing clear documentation to which models are currently supported. 

### Links to any relevant code

https://docs.lula.dev/console/

### Additional context

While the documentation links to the models - it may be worth adding clear levels of support or confidence (table?) for what users should expect. 

Question: Are there any common key bindings we can move up to the console page vs a single model?

### Expected Deliverable

- [ ] Updated console docs

**Comment by meganwolf0** [comment]
Updated console docs in #652 that I believe should encapsulate the intent of this issue

**Comment by meganwolf0** [comment]
Resolved by current docs
