### ISSUE TITLE
Error finding file path when validating a component-definition

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns-labs/lula1#683]
### Environment
Device and OS:  Ubuntu 22.04
App version:   v0.7.0 
Kubernetes distro:  N/A
Kubernetes version:  N/A
provider: N/A

When validating a component-definition that imports a component-definition that contains a remote validation of a file path will error due to current file path lookup functionality and not find the validations.

### Steps to reproduce
1. `git clone https://github.com/defenseunicorns/uds-core.git`
2. `lula validate -f compliance/oscal-component.yaml`
3. Check the log file to see the warning.

### Expected result
assessment-result.yaml is created that contains the imported component-definition's remote validations are tested and satisfied compared to validating that component-definition individually.

### Actual Result
The imported component-definition's remote validations are not found due to current file path functionality.

### Visual Proof (screenshots, videos, text, etc)
![image (2)](https://github.com/user-attachments/assets/824e7072-23fb-406a-91eb-7feaf33fc8e9)
![image (1)](https://github.com/user-attachments/assets/f4c0da39-3818-43fa-999f-706b7b288393)

### Severity/Priority
Moderate/Moderate

**Comment by brandtkeller** [comment]
Should be a duplicate of #684 and should be fixed in `v0.8.0` or `main`

**Comment by CloudBeard** [comment]
Also verified in UDS Core branch where bug was first discovered. No issues with `main`.

Resolved as apart of https://github.com/defenseunicorns/lula/pull/686
