### ISSUE TITLE
Error finding file path when composing a component-definition

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns-labs/lula1#684]
### Environment
Device and OS:  Ubuntu 22.04
App version:   v0.7.0 
Kubernetes distro:  N/A
Kubernetes version:  N/A
provider: N/A

When composing a component-definition that imports a component-definition that contains a remote validation of a file path will error due to current file path lookup functionality and not find the validations.

### Steps to reproduce
1. `git clone https://github.com/defenseunicorns/uds-core.git`
2. `lula tools compose -f compliance/oscal-component.yaml -l debug`
3. Check the log file to see the warning.

### Expected result
component-definition.yaml is created that contains the imported component-definition's remote validations are listed in the back matter when compared to composing that component-definition individually.

### Actual Result
The imported component-definition's remote validations are not found due to current file path functionality.

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/c5635322-055f-4565-82b8-3793812d88ea)

### Severity/Priority
Moderate/Moderate

**Comment by brandtkeller** [comment]
Not able to reproduce the debug messages for `v0.8.0` or `main` of Lula.

**Comment by CloudBeard** [comment]
Also verified in UDS Core branch where bug was first discovered. No issues with `main`.

Resolved as apart of https://github.com/defenseunicorns/lula/pull/686
