### ISSUE TITLE
Add templating to dev commands

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#771]
### Is your feature request related to a problem? Please describe.

Currently `dev validate` and `dev get-resources` doesn't support templating the validation.

### Describe the solution you'd like

- **Given** dev <cmd>
- **When** target is a template
- **Then** target is templated/executed

### Describe alternatives you've considered

Run tools template -> then dev <cmd> on that. This is a stopgap solution but the extra step is mildly annoying

### Expected Deliverable

- [ ] Dev validate supports template configuration + --set to override
- [ ] Dev get-resources supports template configuration + --set to override

**Comment by brandtkeller** [comment]
Adding this to the configuration and templating milestone. #647 is meant to be a catch-all for this work but open to more finely scoped issues.
