### ISSUE TITLE
Create release process for Lula binary

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#96]
Look into process and documentation to support releasing. 

[go releaser](https://goreleaser.com/) is likely an aiding capability to this process.

**Comment by CloudBeard** [comment]
Draft [PR ](https://github.com/defenseunicorns/lula/pull/171) follows same process as go-oscal.

Currently supports Homebrew through PAT but working on possibly switching to GitHub App. May be after deadline before that is created.

**Comment by brandtkeller** [comment]
Closed in #171
